services:
  app:
    build:
      context: ./Barca
      dockerfile: teste.DockerFile
    container_name: webapp_bazar
    command: Barca/node_modules/.bin/ng serve --host 0.0.0.0 --disable-host-check
    ports:
      - 4201:4200
    volumes:
      - .:/app